"""empty message

Revision ID: b27cd3de3852
Revises: 
Create Date: 2020-01-14 05:36:17.578324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27cd3de3852'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estatus',
    sa.Column('id_estatus', sa.Integer(), nullable=False),
    sa.Column('descripcion_estatus', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id_estatus'),
    schema='catalogo'
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('descripcion_rol', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    schema='catalogo'
    )
    op.create_table('revoke_token',
    sa.Column('id_revoke_token', sa.Integer(), nullable=False),
    sa.Column('jti_revoke_token', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id_revoke_token'),
    schema='seguridad'
    )
    op.create_table('entidad_bancaria',
    sa.Column('id_entidad_bancaria', sa.Integer(), nullable=False),
    sa.Column('descripcion_entidad', sa.String(length=40), nullable=True),
    sa.Column('id_estatus', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_estatus'], ['catalogo.estatus.id_estatus'], ),
    sa.PrimaryKeyConstraint('id_entidad_bancaria'),
    schema='catalogo'
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=80), nullable=True),
    sa.Column('password_usuario', sa.String(length=150), nullable=True),
    sa.Column('salt_usuario', sa.String(length=80), nullable=True),
    sa.Column('id_estatus', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_estatus'], ['catalogo.estatus.id_estatus'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    schema='seguridad'
    )
    op.create_table('deuda',
    sa.Column('id_deuda', sa.Integer(), nullable=False),
    sa.Column('descripcion_deuda', sa.String(length=80), nullable=True),
    sa.Column('fecha_deuda', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin_deuda', sa.Date(), nullable=True),
    sa.Column('mensualidades', sa.Boolean(), nullable=True),
    sa.Column('total_deuda', sa.Float(), nullable=False),
    sa.Column('id_estatus', sa.Integer(), nullable=False),
    sa.Column('id_entidad_bancaria', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_entidad_bancaria'], ['catalogo.entidad_bancaria.id_entidad_bancaria'], ),
    sa.ForeignKeyConstraint(['id_estatus'], ['catalogo.estatus.id_estatus'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['seguridad.usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_deuda'),
    schema='persona'
    )
    op.create_table('rol_por_usuario',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_estatus', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_estatus'], ['catalogo.estatus.id_estatus'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['catalogo.rol.id_rol'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['seguridad.usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_rol', 'id_usuario'),
    schema='seguridad'
    )
    op.create_table('mensualidad',
    sa.Column('id_deuda', sa.Integer(), nullable=False),
    sa.Column('id_pago', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('id_estatus', sa.Integer(), nullable=False),
    sa.Column('monto_mensualidad', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_deuda'], ['persona.deuda.id_deuda'], ),
    sa.ForeignKeyConstraint(['id_estatus'], ['catalogo.estatus.id_estatus'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['seguridad.usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_deuda', 'id_pago'),
    schema='persona'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensualidad', schema='persona')
    op.drop_table('rol_por_usuario', schema='seguridad')
    op.drop_table('deuda', schema='persona')
    op.drop_table('usuario', schema='seguridad')
    op.drop_table('entidad_bancaria', schema='catalogo')
    op.drop_table('revoke_token', schema='seguridad')
    op.drop_table('rol', schema='catalogo')
    op.drop_table('estatus', schema='catalogo')
    # ### end Alembic commands ###
